version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - ${{ github.repository_owner }}  # edit to assign a different assignee "username"
  # Check for Docker image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - ${{ github.repository_owner }}  # edit to assign a different assignee "username"