# Workflow to update all Dockerfiles when a new version of Caddy is available and create a new release and tag
name: Update, create tag and release

# Controls when the action will run
on:
  workflow_dispatch:  # allows to run the workflow manually from the Actions tab
  push:
    branches: dev
    paths:
      - caddy-cloudflare-crowdsec/Dockerfile  # file updated by Dependabot used as reference

# Environment variables available to all jobs and steps in this workflow
env:
  CADDY_BUILDS: |  # list of all Caddy Docker custom builds
    caddy-cloudflare-crowdsec

# Jobs to run once the workflow is triggered
jobs:
  # Job to parse the Caddy version from the reference Dockerfile
  metadata:
    name: Update all Dockerfiles
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Parse Caddy version
        id: version
        run: echo "version=$(grep -Eo 'caddy:[0-9]+\.[0-9]+\.[0-9]+$' caddy-cloudflare-crowdsec/Dockerfile | cut -d ':' -f2)" | tee -a $GITHUB_OUTPUT
  
  # Job to update the Caddy version in all Dockerfiles and create a tag
  update:
      name: Update Caddy and create tag
      runs-on: ubuntu-latest
      needs: metadata

      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: dev

      - name: Replace Caddy version in all Dockerfiles
        run: |
          for caddy_build in $CADDY_BUILDS; do
            sed -i "s/caddy:[0-9]\+\.[0-9]\+\.[0-9]\+/caddy:${{ needs.metadata.outputs.version }}/g" ./$caddy_build/Dockerfile
          done

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Commit push changes
        run: |
          git add ./*/Dockerfile
          if [ "$(git diff HEAD)" ]
          then
            git commit -Sm "Bump Caddy version to v${{ needs.metadata.outputs.version }} in all Dockerfiles"
            git push
          else
            echo "No changes detected"
          fi
        
      - name: Create and push tag
        run: |
          git tag -fs v${{ needs.metadata.outputs.version }}-test -m "Docker images built with Caddy v${{ needs.metadata.outputs.version }}"
          git push --tags -f

  # Job to create a release
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [metadata, update]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Generate release text
        id: text
        run: |
          echo "RELEASE_TEXT<<EOF" >> $GITHUB_ENV
          for caddy_build in $CADDY_BUILDS; do
            echo "- $caddy_build: [Source](https://github.com/serfriz/caddy-cloudflare-crowdsec/tree/main/$caddy_build) / \
            [GitHub Package](https://ghcr.io/serfriz/$caddy_build) / [Docker Hub](https://hub.docker.com/r/serfriz/$caddy_build) / \
            [Quay Package](https://quay.io/serfriz/$caddy_build)" >> $GITHUB_ENV
          done
          echo "EOF" >> $GITHUB_ENV

      - name: Push release to github repository including tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.metadata.outputs.version }}-test
          body: |
            Release notes: https://github.com/caddyserver/caddy/releases/tag/v${{ needs.metadata.outputs.version }}

            Caddy custom builds:
            ${{ env.RELEASE_TEXT }}